-- Sprint 3 Security Hardening
-- 2026-05-15
--
-- NOTA: O hardening de Sprint 3 foi aplicado via:
--   1. Fix de RLS em 20260513_070_rls_fix.sql (vazamento de tenant fechado)
--   2. Mudanças em application layer (middleware.ts, tenant-context.ts)
--   3. Esta migration está vazia intencionalmente — o hardening foi feito
--      em migrations anteriores desta sprint.
--
-- TODO: Verificar se há hardening adicional de DB a aplicar (ADR-001).
